#!/bin/sh

locker="waylock --init-color 0x000000 --input-color 0x126348 --fail-color 0xb53126"

#key binds
##launch
riverctl map normal Super A spawn foot
riverctl map normal Super W spawn firefox
riverctl map normal Super Semicolon spawn "$locker"
riverctl map normal Super E spawn 'wofi -S run'
riverctl map normal Super+Shift E spawn 'wofi -S drun'
riverctl map normal Super M spawn 'rofimoji'

##media
###audio
riverctl map normal None XF86AudioRaiseVolume spawn 'pamixer -i 5'
riverctl map normal None XF86AudioLowerVolume spawn 'pamixer -d 5'
riverctl map normal None XF86AudioMute spawn 'pamixer --toggle-mute'

###mpris media
riverctl map normal None XF86AudioMedia spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPlay spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev spawn 'playerctl previous'
riverctl map normal None XF86AudioNext spawn 'playerctl next'

###brightness
riverctl map normal None XF86MonBrightnessUp spawn 'brightnessctl set 5%+'
riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

###background
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

##river control
riverctl map normal Super Q close
riverctl map normal Control+Alt Delete exit

##cycle focus
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

##monitors
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

##main management
riverctl map normal Super Return zoom
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

##move
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

##snap to edge
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

##resize
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

##mouse move
riverctl map-pointer normal Super BTN_LEFT move-view

##mouse resize
riverctl map-pointer normal Super BTN_RIGHT resize-view

#tags
for i in $(seq 1 9)
do
    tags=$((1 << (i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super "$i" set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift "$i" set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control "$i" toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Tab focus-previous-tags
riverctl map normal Super+Shift Tab send-to-previous-tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

#inputs
riverctl set-repeat 50 300
riverctl input pointer-1739-52759-SYNA32A9:00_06CB:CE17_Touchpad tap enabled
riverctl map-switch normal lid close spawn "systemctl suspend"

#startup

##status
riverctl spawn waybar

##idle
#
idlecmd="$(printf "swayidle timeout 300 'wlopm --off \*' resume 'wlopm --on \*' timeout 600 'systemctl suspend' before-sleep '%s'" "$locker")"
riverctl spawn "$idlecmd"

##tiling
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6
