# xs".*?"<cr><a-)> to cycle through options
set-option global disabled_hooks '' #'.*-indent' '.*-highlight' '.*-indent|.*-highlight'
set-option global ui_options terminal_assistant=off terminal_set_title=false

map global insert <tab> '<a-;><a-gt>'
map global insert <s-tab> '<a-;><a-lt>'

map global insert <c-[> '<esc>'
map global prompt <c-[> '<esc>'

colorscheme tomorrow-night

# plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug 'andreyorst/plug.kak' noload %{
    map global user p %{: plug-list<ret>} -docstring 'plug.kak list'
}
plug 'delapouite/kakoune-buffers' %{
    map global user b %{: enter-buffers-mode<ret>} -docstring 'buffers'
    map global user B %{: enter-user-mode -lock buffers<ret>} -docstring 'buffers %(lock)'
}
plug 'kak-lsp' load-path '/usr/share/kak-lsp/rc' %{
    lsp-inlay-diagnostics-enable global
    hook global WinSetOption filetype=(rust|cpp|c|zig) %{
        lsp-enable-window
        map window user d %{: enter-user-mode lsp<ret>} -docstring 'LSP mode'
    }
}
