# xs".*?"<cr><a-)> to cycle through options
set-option global disabled_hooks ".*-indent" #".*-highlight" ".*-indent|.*-highlight"
set-option global ui_options terminal_assistant=off terminal_set_title=false

hook global WinSetOption filetype=sh %{ set-option buffer lintcmd 'shellcheck -f gcc' }

map global insert <tab> '<a-;><a-gt>'
map global insert <s-tab> '<a-;><a-lt>'

colorscheme tomorrow-night

# plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
}

hook global WinSetOption filetype=(rust) %{
    lsp-enable-window
}

map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
