colorscheme tomorrow-night

#set-option global startup_info_version 99999999
set-option global startup_info_version -1
set-option global ui_options terminal_set_title=false
set-option global autoreload yes
set-option global spell_lang 'en_US'

hook global ModuleLoaded sway|wayland %{
    set-option global termcmd 'foot -a "foot.floating" sh -c'
}
hook global WinSetOption filetype=javascript %{
    set-option buffer indentwidth 2
}
hook global WinSetOption filetype=c %{
    set-option buffer indentwidth 0
}
hook global BufCreate \*scratch.* %{
    execute-keys %{%d}
}

map global insert <a-e> '<esc>x|emmet<ret>'

map global insert <tab> '<a-;><a-gt>'
map global insert <s-tab> '<a-;><a-lt>'
map global insert <c-h> '<backspace>'
map global insert <c-d> '<esc>!date -u +%FT%TZ<ret>'

map global user i ':set buffer indentwidth %val{count}<ret>'

hook global WinSetOption filetype=sh %{
    set-option buffer lintcmd 'shellcheck -f gcc'
}

source "%val{config}/plugins.kak"
