#!/usr/bin/env lua

local function usage()
    local help = "Usage:" ..
        "\n<BIN> (tags)+ (-- (files)*)?"
    print(help)
end

local args = {...}
local cmd = 'rg -wl'

local i = 1
while i <= #args do
    if (args[i] == "--") then break end
    cmd = cmd .. [[ -e '\B]] .. args[i] .. [[\b']]
    i = i + 1
end

if i == 1 then
    usage()
    os.exit(1)
else
    i = i + 1
    while i <= #args do
        cmd = cmd .. ' ' .. args[i]
        i = i + 1
    end
end

os.execute(cmd)
