#!/bin/sh
alias g='kak'
alias gt='cd ~/Documents/todo'
alias gg='g ~/Documents/todo/todo.txt'
alias gi='cd ~/Documents/school'
alias gD='cd ~/Documents'
alias gd='cd ~/Documents/drawing'
alias gdr='cd ~/Documents/drawing/refs'
alias gn='cd ~/Documents/notes'
alias gz='cd ~/Documents/notes/zet'

#alias fd='cd $(find -type d | fzf)'

alias ls='ls -v --color=auto'
