#!/bin/sh
alias g='vi'
alias gg='g ~/Documents/todo.txt'
alias gi='cd ~/Documents/school'
alias gn='cd ~/Documents/notes'
alias gD='cd ~/Documents'
alias gd='cd ~/Documents/drawing'
alias gdr='cd ~/Documents/drawing/refs'
alias gz='cd ~/Documents/notes/zet'

alias fd='cd $(find -type d | fzf)'

alias ls='ls -v --color=auto'

# school stuff
## Useful aliases
alias cms='ssh -Y jtan@cmslpc-sl7.fnal.gov'
alias kcms='kinit jtan@FNAL.GOV'
