#!/bin/sh
# AUDIO="$(amixer get 'Master' | tail -n 1 | tr ' ' '\n' | tail -n 2 | tr -d '\n' | sed 's/ $/\n/')"
BATTERY="$(acpi | cut -d , -f 2 | tr -d ' ')"
# BRIGHTNESS="$(printf "%.1f" "$(xbacklight)")"
TIME="$(date +"%m-%d %R")"
printf " B:%s | T:%s " "$BATTERY" "$TIME"
#printf "B:%s\nT:%s" "$BATTERY" "$TIME"
