#!/bin/sh
# maybe refactor?
# AUDIO="$(amixer get 'Master' | tail -n 1 | sed 's/].*//;s/.*\[//')"
# BRIGHTNESS="$(printf "%.1f" "$(xbacklight)")"
if [ $# -eq 0 ]; then
	BATTERY="$(acpi | cut -d , -f 2 | sed 's/^ *//')"
	TIME="$(date +"%m-%d %R")"
	printf " B:%s | T:%s " "$BATTERY" "$TIME"
else
	BATTERY="$(acpi | cut -d , -f 2,3 | sed 's/^ *//')"
	TIME="$(date)"
	printf "B:%s\nT:%s\n" "$BATTERY" "$TIME"
	printf "VPN:\n"
	nordvpn status | head -n 2 | cut -d ':' -f 2
	cal -3
fi
