#!/bin/sh
queue="$(mktemp -t queue.XXX)"
trap 'rm "$queue";exit' INT

while : ; do
	[ -s "$queue" ] || \
		find . -type f \( -name "*.opus" -o -name "*.aac" \) | shuf > "$queue"
	curr="$(head -n 1 "$queue")"
	clear
	printf "%s\n" "$curr"
	mpv --really-quiet "$curr"
	sed -i '1d' "$queue"
done
